# PowerShell Modules to install from PSGallery
psModules:
  - Terminal-Icons # Icons for Oh-My-Posh

# Applications to install via WinGet
WinGetApps:
  # --------------------------------------------------------------------------
  # Core System Utilities & Enhancements
  #    - General-purpose tools essential for system management or fundamental user experience.
  # --------------------------------------------------------------------------
  - name: 7-Zip
    id: 7zip.7zip
  - name: Git
    id: Git.Git
  - name: WinDirStat
    id: WinDirStat.WinDirStat
  - name: Oh My Posh
    id: JanDeDobbeleer.OhMyPosh
  - name: PowerToys
    id: Microsoft.PowerToys
  - name: Windows Terminal Preview
    id: Microsoft.WindowsTerminal.Preview
  - name: Vivaldi Browser
    id: Vivaldi.Vivaldi
  - name: Microsoft Windows Subsystem Linux
    id: Microsoft.WSL
  - name: K-Lite Mega Codec Pack
    id: CodecGuide.K-LiteCodecPack.Mega

  # --------------------------------------------------------------------------
  # Communication & Collaboration
  #    - Apps for messaging, video calls, and teamwork.
  # --------------------------------------------------------------------------
  - name: WhatsApp
    id: 9NKSQGP7F2NH # WinGet ID for WhatsApp Desktop
  - name: Keybase
    id: Keybase.Keybase # Secure messaging and file sharing
  - name: KeePass
    id: DominikReichl.KeePass
  - name: Microsoft Teams
    id: Microsoft.Teams
  - name: Discord
    id: Discord.Discord

  # --------------------------------------------------------------------------
  # Development & DevOps Tools
  #    - Applications specific to software development, version control, and infrastructure management.
  # --------------------------------------------------------------------------
  - name: Visual Studio Code
    id: Microsoft.VisualStudioCode
  - name: Docker Desktop
    id: Docker.DockerDesktop
  - name: Azure CLI
    id: Microsoft.AzureCLI

  # --------------------------------------------------------------------------
  # Productivity & Office
  #    - General office suites, note-taking, and task management.
  # --------------------------------------------------------------------------
  - name: Notepad++
    id: Notepad++.Notepad++
  - name: Microsoft Office # Note: WinGet often installs the "Microsoft 365" app, which then facilitates Office install
    id: Microsoft.Office
  - name: Notion
    id: Notion.Notion
  - name: SiYuan
    id: B3log.SiYuan


  # --------------------------------------------------------------------------
  # Other
  #
  # --------------------------------------------------------------------------
  - name: OBS Studio
    id: OBSProject.OBSStudio
  - name: Parsec
    id: Parsec.Parsec # Remote desktop for low-latency streaming/gaming
  - name: VLC media player
    id: VideoLAN.VLC

  # --------------------------------------------------------------------------
  # Specialized Tools & Runtimes
  #    - Applications that provide specific hardware control, runtimes, or foundational libraries.
  # --------------------------------------------------------------------------
  - name: Logitech Options+
    id: Logitech.OptionsPlus
  - name: Logitech G HUB
    id: Logitech.GHUB
  - name: Visual C++ Redistributables (2010 x86)
    id: Microsoft.VCRedist.2010.x86
  - name: Visual C++ Redistributables (2012 x86)
    id: Microsoft.VCRedist.2012.x86
  - name: Visual C++ Redistributables (2013 x86)
    id: Microsoft.VCRedist.2013.x86
  - name: Visual C++ Redistributables (2013 x64)
    id: Microsoft.VCRedist.2013.x64
  - name: Visual C++ Redistributables (2015+ x64)
    id: Microsoft.VCRedist.2015+.x64
  - name: Visual C++ Redistributables (2015+ x86)
    id: Microsoft.VCRedist.2015+.x86
  - name: .NET Desktop Runtime 8
    id: Microsoft.DotNet.DesktopRuntime.8

  # --------------------------------------------------------------------------
  # Security & Privacy
  #    - Applications focused on protecting user data and online anonymity.
  # --------------------------------------------------------------------------
  - name: NordVPN
    id: NordSecurity.NordVPN

  # --------------------------------------------------------------------------
  # AI / Machine Learning Tools
  #    - Applications specifically designed for AI development or inference.
  # --------------------------------------------------------------------------
  - name: LM Studio
    id: ElementLabs.LMStudio

  # --------------------------------------------------------------------------
  # 3D Printing / CAD
  #    - For specialized hardware control and design.
  # --------------------------------------------------------------------------
  - name: Bambu Studio
    id: Bambulab.Bambustudio

# VSCode Extensions to install
VSCodeExtensions:
  - name: Remote Containers
    id: ms-vscode-remote.remote-containers
  - name: WSL
    id: ms-vscode-remote.remote-wsl
  - name: Powershell
    id: ms-vscode.powershell
  - name: GitLens
    id: eamodio.gitlens
  - name: Azure PowerShell Tools
    id: azps-tools.azps-tools
  - name: HashiCorp Terraform
    id: hashicorp.terraform
  - name: Gemini Code Assist
    id: google.geminicodeassist
  - name: Azure PowerShell Tools
    id: azps-tools.azps-tools



# Registry settings
RegistrySettings:
  - description: Folder Options - Hide extension for know file types - Disable
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    key: HideFileExt
    value: 0
  - description: Display full path in the title bar - Enable
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    key: ShowFullPath
    value: 1
  - description: Privacy - Show recently used files - Disable
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    key: Start_TrackDocs
    value: 0
  - description: Privacy - Show frequently used folder - Disable
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    key: Start_TrackFolders
    value: 0